CREATE TABLE client(
  id SERIAL PRIMARY KEY,
  client_name VARCHAR(255) NOT NULL UNIQUE,
  age INTEGER NOT NULL CHECK (age >0),  
  gender VARCHAR(6) NOT NULL,  
  occupation VARCHAR(255) NOT NULL,
  nationality VARCHAR(255) NOT NULL
);

CREATE TABLE restaurant(
  id SERIAL PRIMARY KEY,
  restaurant_name VARCHAR(255) NOT NULL UNIQUE,
  category VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL
);

CREATE TABLE dishes(
id SERIAL PRIMARY KEY,
dish VARCHAR(255) NOT NULL
);

CREATE TABLE orders(
  id SERIAL PRIMARY KEY,
  restaurant_id INTEGER NOT NULL REFERENCES restaurant,
  dishes_id INTEGER NOT NULL REFERENCES dishes,
  price INTEGER NOT NULL CHECK (price >=0),
  visit_date DATE NOT NULL,
  client_id INTEGER NOT NULL REFERENCES client
);

